const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  topics: state => state.topic.topics,
  topic: state => state.topic.topic,
  unRevierTopics: state => state.topic.unRevierTopics,
  sevenDaysTopicChangeArr: state => state.topic.sevenDaysTopicChangeArr,
  users: state => state.userManagement.users,
  userTotalPages: state => state.userManagement.totalPages,
  roleList: state => state.userManagement.roleList,
  sevenDaysUserChangeArr: state => state.userManagement.sevenDaysUserChangeArr
}
export default getters
